import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {initialWorld,chatSend,unlockContact,socialSend,tickWorld,nextJstHour,relativeTime,visible,itemTime,validateConfig,validateWorld,migrateLegacy} from '../assets/world.js';
const c=JSON.parse(readFileSync(new URL('../content/scenario.json',import.meta.url)));
const start=Date.parse('2026-09-27T08:00:00Z');
test('valid content and initial world',()=>{assert.deepEqual(validateConfig(c),[]);assert.ok(validateWorld(initialWorld(c,start)));});
test('stage gating, contact gating, and invitation',()=>{let w=initialWorld(c,start);w=chatSend(w,c,'haru','みかん',start);assert.equal(w.step,0);assert.equal(unlockContact(w,c,'manager').contacts.length,1);w=chatSend(w,c,'haru','りんご',start+1);assert.equal(w.step,1);w=chatSend(w,c,'haru','りんご',start+2);assert.equal(w.step,1);w=unlockContact(w,c,'aoi');assert.ok(w.contacts.includes('aoi'));w=chatSend(w,c,'aoi','写真',start+3);assert.equal(w.step,1);w=chatSend(w,c,'haru','みかん',start+4);assert.equal(w.step,2);w=chatSend(w,c,'aoi','写真',start+5);assert.equal(w.step,3);w=unlockContact(w,c,'manager');w=chatSend(w,c,'manager','星座',start+6);assert.equal(w.step,4);});
test('delay survives serialization and only fires once; late open catches up',()=>{let w=chatSend(initialWorld(c,start),c,'haru','りんご',start);w=JSON.parse(JSON.stringify(w));assert.equal(tickWorld(w,c,start+3599999).messages.length,w.messages.length);w=tickWorld(w,c,start+3600000);assert.ok(w.messages.some(m=>m.id==='scheduled:apple'));assert.deepEqual(tickWorld(w,c,start+7200000),w);});
test('19:00 JST strict boundary chooses following day at exact hour',()=>{assert.equal(nextJstHour(Date.parse('2026-09-27T09:59:59Z'),19),Date.parse('2026-09-27T10:00:00Z'));assert.equal(nextJstHour(Date.parse('2026-09-27T10:00:00Z'),19),Date.parse('2026-09-28T10:00:00Z'));});
test('random publication remains stable and respects unlock',()=>{const w=initialWorld(c,start,()=>0.5),p=c.posts.find(x=>x.randomMinutes);assert.equal(itemTime(p,w),start+6.5*60000);assert.equal(visible(p,w,start+60000),false);assert.equal(visible(p,w,start+7*60000),true);assert.equal(visible(c.blogs[1],w,start+99999999),false);assert.equal(itemTime(p,JSON.parse(JSON.stringify(w))),itemTime(p,w));});
test('SNS keyword replies, unmatched silence, and own isolated timeline',()=>{let w=initialWorld(c,start);w=socialSend(w,c,'post','写真について知っている人はいませんか','',start);assert.equal(w.posts.length,1);assert.equal(w.replies[0].account,'aoi');w=socialSend(w,c,'dm','こもれび','aoi',start+10);assert.equal(w.dms.length,2);w=socialSend(w,c,'dm','こんにちは','aoi',start+20);assert.equal(w.dms.length,3);assert.equal(initialWorld(c,start).posts.length,0);});
test('relative ages and old state migration',()=>{assert.equal(relativeTime(start-10*3600000,start),'10時間前');assert.equal(relativeTime(start-3*86400000,start),'3日前');const w=migrateLegacy({version:1,step:2,messages:[],unlockedAt:[start-10,start-5]},c,start);assert.equal(w.step,2);assert.ok(w.fired.includes('rule:orange'));assert.ok(validateWorld(w));});
test('reject malformed config and imports',()=>{const bad=structuredClone(c);bad.rules[0].image='javascript:alert(1)';assert.ok(validateConfig(bad).length);assert.equal(validateWorld({version:2}),false);const bad2=structuredClone(c);bad2.posts[0].account='missing';assert.ok(validateConfig(bad2).length);});
test('timed non-official content emits a persisted publication change',()=>{let w=tickWorld(initialWorld(c,start,()=>0),c,start);const next=tickWorld(w,c,start+16*60000);assert.ok(next.fired.includes('published:morning'));assert.ok(next.fired.includes('published:p-random'));assert.notDeepEqual(next,w);});
test('old progress retains a route to newly introduced contacts',()=>{const w=migrateLegacy({version:1,step:2,messages:[],unlockedAt:[start-10,start-5]},c,start);assert.ok(w.messages.some(m=>m.invite==='aoi'));assert.ok(w.messages.some(m=>m.invite==='manager'));});

test('editor rejects malformed nested values without throwing',()=>{for(const mutate of [x=>x.rules[0].keyword=42,x=>x.contacts[0]=null,x=>x.management.members={},x=>x.recorder.tracks[0]=null,x=>x.events[0].price='free']){const bad=structuredClone(c);mutate(bad);assert.ok(validateConfig(bad).length);}});
